### ISSUE TITLE
i know this is an old mod, and this might be a simple fix anyways, but...

### ISSUE THREAD

**Issue by meh721** [AngrySoundTech/BetterRecords#1]
# Version Info 
Forge version:  14.23.5.2859
Mod version: 1.6.2

# Description
Link to crash log: (please use [gist] or [pastebin]. Do **not** paste a log as text or attach a file)

Steps to reproduce:
1.  trying to etch any song at all from dropbox results in a application/json is not supported error

I've tried looking up several tutorials, and I'm doing what people say to do to add a song (using dl.dropboxusercontent) but it doesn't seem to work anymore. it was doing just fine about a month or so ago and now this, any solutions?

[gist]: https://gist.github.com/
[pastebin]: https://pastebin.com/

**Comment by Sergio03FS** [comment]
Hi, I have the same problem. It worked some months ago but now appears that message about application/json.  Have you managed to solve it? @meh721

**Comment by nikfzn** [comment]
Hello why when I write the name of the record and paste the URL I write IO Exception

**Comment by Rafaelprozx** [comment]
use a command in command block

`give -Player- betterrecords:record 1 0 {color:16777215,songs:[{size:8,author:"-Author-",name:" -Disk Name-",url:"-URL-"}]}`

change -Player- for the player who receive the disk
change -Author- and -Disk Name- for data the disk must show
change -URL- for the dropbox link

sorry for bad english #

**Comment by meh721** [comment]
> use a command in command block
> 
> `give -Player- betterrecords:record 1 0 {color:16777215,songs:[{size:8,author:"-Author-",name:" -Disk Name-",url:"-URL-"}]}`
> 
> change -Player- for the player who receive the disk change -Author- and -Disk Name- for data the disk must show change -URL- for the dropbox link
> 
> sorry for bad English #

hey! sorry for the long wait, I've just been out of Minecraft for a bit, but I just tried your solution just now. it seems to work, but no matter what I do, when the record plays, no sound is emitted at all, any way to fix that?

**Comment by Ishumire** [comment]
Found this video, and it currently works. Hopefully it stays that way.
https://www.youtube.com/watch?v=vejznNmVY4o&ab_channel=DpizzaGuy

**Comment by MMDGLaDOS** [comment]
> Found this video, and it currently works. Hopefully it stays that way. https://www.youtube.com/watch?v=vejznNmVY4o&ab_channel=DpizzaGuy

Sadly doesnt work idk what has happened to the Mod but nothing seems to work now

**Comment by JackyBorderCollie** [comment]
I ran into the same issue, but I know of a fix. Upload the music you want to play to Mediafire, copy the link to download it (should take you to the Mediafire file download page). Now, right-click Download and select Copy Link Address. Paste that URL into the text box for URLs in the etcher, and there you go!

**Comment by AngrySoundTech** [comment]
Closing this issue, as we're in the process of a full rewrite of the mod for 1.20
