### ISSUE TITLE
For those that want an updated version

### ISSUE THREAD

**Issue by Alexsys** [AngrySoundTech/BetterRecords#2]
A legend named AlexS1105 has made a forked improved version that fixed the issue that the issue below me shows,

https://github.com/AlexS1105/BetterRecords

If you want to play dropbox records, you must add 1 to the =0   in the end of the dropbox url you copied
example:
https://www.dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=0   (this is how it copies originally)
https://www.dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=1   (you change it to =1)

dl means download, the mod downloads the music, thus playing it. so we enable download, then it can download the music to the record you etch in the mod

**Comment by MMDGLaDOS** [comment]
soo how do we fix it exactly? why not just upload the fix on curse?

**Comment by InuYasha86000** [comment]
unless the original creator of BetterRecords gives permission for the fix to be uploaded to curse, or the original author accepts the fix and uploads it themselves, Alexsys can't upload it to curse without possibility of getting a warning, a takedown request, or something more severe. believe me, the fix is greatly appreciated, but due to not being able to upload it to curse may end up me removing the mod entirely from my modpack as it's public.

**Comment by CapoFantasma97** [comment]
> A legend named AlexS1105 has made a forked improved version that fixed the issue that the issue below me shows,
> 
> [AlexS1105/BetterRecords](https://github.com/AlexS1105/BetterRecords)
> 
> If you want to play dropbox records, you must add 1 to the =0 in the end of the dropbox url you copied example: [dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=0](https://www.dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=0) (this is how it copies originally) [dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=1](https://www.dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=1) (you change it to =1)
> 
> dl means download, the mod downloads the music, thus playing it. so we enable download, then it can download the music to the record you etch in the mod

The fork is down, please give us a way :(

**Comment by InuYasha86000** [comment]
I would love for the fork to be issued to curseforge but I know the original creator of  etterrecords was very closed with his code, so unless he gives specific permission for the fix, our bopes of the mod working properly on 1.12.2 will not happen sadly.

**Comment by AngrySoundTech** [comment]
> I would love for the fork to be issued to curseforge but I know the original creator of etterrecords was very closed with his code, so unless he gives specific permission for the fix, our bopes of the mod working properly on 1.12.2 will not happen sadly.

Any current version of this mod is licensed MIT, and developers are free to do as they wish in accordance with the license, which is extremely permissive and allows people to do pretty much anything

**Comment by Alexsys** [comment]
> > A legend named AlexS1105 has made a forked improved version that fixed the issue that the issue below me shows,
> > [AlexS1105/BetterRecords](https://github.com/AlexS1105/BetterRecords)
> > If you want to play dropbox records, you must add 1 to the =0 in the end of the dropbox url you copied example: [dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=0](https://www.dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=0) (this is how it copies originally) [dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=1](https://www.dropbox.com/s/puwr08r3w88440l/fiejifeij.mp3?dl=1) (you change it to =1)
> > dl means download, the mod downloads the music, thus playing it. so we enable download, then it can download the music to the record you etch in the mod
> 
> The fork is down, please give us a way :(

I still have the mod in my game,
here's the jar.

https://www.dropbox.com/scl/fi/asipqxpgtte45zyrqrgkz/BetterRecords-1.12.2-1.6.3.jar?rlkey=6u2rjqjwnswxsxnwoclad91vl&dl=0

enjoy it man.

**Comment by InuYasha86000** [comment]
a lot of people are probly appreciative of you posting it here, my problem is it would have to be up on curseforge as it was once part of my modpack. thank you though

**Comment by Alexsys** [comment]
> a lot of people are probly appreciative of you posting it here, my problem is it would have to be up on curseforge as it was once part of my modpack. thank you though

if you want, i can upload it on curseforge for your ease
why not

**Comment by Alexsys** [comment]
> a lot of people are probly appreciative of you posting it here, my problem is it would have to be up on curseforge as it was once part of my modpack. thank you though

https://legacy.curseforge.com/minecraft/mc-mods/better-records-fixed

enjoy
you'll see it soon when it gets approved

**Comment by InuYasha86000** [comment]
one thing I wish they had fixed as well is the multiplayer dyable record bug, but at least we have a working music player again.

**Comment by InuYasha86000** [comment]
just checked the project page and there is no download/file available. I think the file has been flagged or something.

**Comment by Alexsys** [comment]
> just checked the project page and there is no download/file available. I think the file has been flagged or something.

https://i.imgur.com/aBAvgXp.png

still under manual review :)

**Comment by AngrySoundTech** [comment]
Closing this issue, as we're in the process of a full rewrite of the mod for 1.20
