### ISSUE TITLE
alternate mod option

### ISSUE THREAD

**Issue by meh721** [AngrySoundTech/BetterRecords#3]
I know I shouldn't probably go recommending other mods on a mods github page, but it seems this has been abandoned, plus I don't think even around 20 people on this planet knows this mods existence... SO there's a mod that adds in a straight up music player you can find on curseforge called, get this: music player. https://www.curseforge.com/minecraft/mc-mods/music-player here's a link to it. right now it is for FORGE 1.8 and above and only requires one utility mod to work. it allows you to look up songs from YouTube and put them in a playlist (I know I know, its not immersive and there's no video player) but seriously, from all the times I've played with it? it works like a charm. You're welcome.

**Comment by InuYasha86000** [comment]
I think one problem with Music Player is it's client only and not able to play music that people around you in game can hear. that's what made BetterRecords special was the ability to play a song in a server or multiplayer world and have other players around you hear the music.

**Comment by AngrySoundTech** [comment]
Closing this issue, as we're in the process of a full rewrite of the mod for 1.20
