### ISSUE TITLE
it stops  working

### ISSUE THREAD

**Issue by Epipgg** [AngrySoundTech/BetterRecords#4]
I downloaded the latest version of this mod and at first everything was perfect and i wasnt having any problems but after some time the records suddenly stop working and the only way i know to fix this is by creating new records every time but it gets annoying after a few times. I hope this can be fixed or i can find a better way to deal with this. Thanks

**Comment by AngrySoundTech** [comment]
Closing this issue, as we're in the process of a full rewrite of the mod for 1.20
